USE EMPLOYEE_DIRECTORY;

DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL
);

INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, BIRTHDATE, PHONE_NUMBER) 
VALUES 
("Mohanad", "Ayman", "mohanadaly@gmail.com", STR_TO_DATE("12/11/1998", "%d/%m/%Y"), "01000000000"),
("Mohab", "Ayman", "mohabaly@gmail.com", STR_TO_DATE("18/10/1995", "%d/%m/%Y"), "01000000000"),
("Nouran", "Ayman", "nouran@gmail.com", STR_TO_DATE("12/10/1997", "%d/%m/%Y"), "01000000000")
;

CREATE TABLE USERS (
USER_ID INT NOT NULL,
USERNAME VARCHAR(20) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(100) NOT NULL,
ENABLED TINYINT NOT NULL DEFAULT 1,
FOREIGN KEY (USER_ID) REFERENCES EMPLOYEES(ID)
);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD)
VALUES 
(1, "mohanad", "{noop}mohanad"),
(2, "mohab", "{noop}mohab"),
(3, "nouran", "{noop}nouran")
;

CREATE TABLE ROLES(
ROLE INT NOT NULL PRIMARY KEY,
AUTHORITY VARCHAR(15) NOT NULL
);

INSERT INTO ROLES VALUES (1, "ROLE_EMPLOYEE"), (2, "ROLE_MANAGER"), (3, "ROLE_ADMIN");

CREATE TABLE AUTHORITIES (
USERNAME VARCHAR(20) NOT NULL,
ROLE INT NOT NULL,
PRIMARY KEY (USERNAME, ROLE),
FOREIGN KEY (ROLE) REFERENCES ROLES(ROLE),
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

INSERT INTO AUTHORITIES 
VALUES 
("mohanad", 1),
("mohanad", 2),
("mohanad", 3),
("mohab", 1),
("mohab", 2),
("nouran", 1)
;