USE EMPLOYEE_DIRECTORY;

DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL
);

INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, BIRTHDATE, PHONE_NUMBER) 
VALUES 
("Mohanad", "Ayman", "mohanadaly@gmail.com", STR_TO_DATE("12/11/1998", "%d/%m/%Y"), "01000000000"),
("Mohab", "Ayman", "mohabaly@gmail.com", STR_TO_DATE("18/10/1995", "%d/%m/%Y"), "01000000000"),
("Nouran", "Ayman", "nouran@gmail.com", STR_TO_DATE("12/10/1997", "%d/%m/%Y"), "01000000000")
;

CREATE TABLE USERS (
USER_ID INT NOT NULL PRIMARY KEY,
USERNAME VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
ENABLED TINYINT NOT NULL DEFAULT 1,
FOREIGN KEY (USER_ID) REFERENCES EMPLOYEES(ID)
);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD)
VALUES 
(1, "mohanad", "$2a$10$V/Y7G4lBUGsn0YoGLcDsceMp0oRQFROUSfmRcskSum0k6boyoQNiC"),
(2, "mohab", "$2a$10$y4Zq6EGYUSaUMtYWymo72u5BA9MdI72.yP3O5/0NV8sRIOBJw9sdG"),
(3, "nouran", "$2a$10$KkfrU9G.i8rolQtCCzB4BO0uIteoi10O3VA5zkpV042fQ0tcCT3Nyn")
;

CREATE TABLE ROLES(
ROLE INT NOT NULL PRIMARY KEY,
AUTHORITY VARCHAR(15) NOT NULL
);

INSERT INTO ROLES VALUES (1, "ROLE_EMPLOYEE"), (2, "ROLE_MANAGER"), (3, "ROLE_ADMIN");

CREATE TABLE AUTHORITIES (
USER_ID INT NOT NULL,
ROLE INT NOT NULL,
PRIMARY KEY (USER_ID, ROLE),
FOREIGN KEY (ROLE) REFERENCES ROLES(ROLE),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

INSERT INTO AUTHORITIES 
VALUES 
("1", 1),
("1", 2),
("1", 3),
("2", 1),
("2", 2),
("3", 1)
;